# Generated by Django 5.1 on 2024-08-18 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Port',
            fields=[
                ('code', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'ports',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('price', models.IntegerField()),
                ('dest_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_prices', to='api.port')),
                ('orig_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_prices', to='api.port')),
            ],
            options={
                'db_table': 'prices',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('slug', models.SlugField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('parent_slug', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subregions', to='api.region')),
            ],
            options={
                'db_table': 'regions',
            },
        ),
        migrations.AddField(
            model_name='port',
            name='parent_slug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ports', to='api.region'),
        ),
    ]
