# Generated by Django 5.1 on 2024-08-20 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='port',
            name='parent_slug',
            field=models.ForeignKey(db_column='parent_slug', on_delete=django.db.models.deletion.CASCADE, related_name='ports', to='api.region'),
        ),
        migrations.AlterField(
            model_name='price',
            name='dest_code',
            field=models.ForeignKey(db_column='dest_code', on_delete=django.db.models.deletion.CASCADE, related_name='destination_prices', to='api.port'),
        ),
        migrations.AlterField(
            model_name='price',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='price',
            name='orig_code',
            field=models.ForeignKey(db_column='orig_code', on_delete=django.db.models.deletion.CASCADE, related_name='origin_prices', to='api.port'),
        ),
        migrations.AlterField(
            model_name='region',
            name='parent_slug',
            field=models.ForeignKey(blank=True, db_column='parent_slug', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subregions', to='api.region'),
        ),
    ]
