version: '3.8'

services:
  db:
    build: .
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./rates.sql:/docker-entrypoint-initdb.d/rates.sql
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
